spring:
  application:
    name: pokedex
  datasource:
    url: jdbc:mysql://localhost:3306/pokedex
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: simple  # Use simple cache instead of redis for now

server:
  port: 8080

pokeapi:
  base-url: https://pokeapi.co/api/v2

logging:
  level:
    com.pokedex: INFO